version: 0.0
os: linux
files:
  - source: /index.html
    destination: /root/efs/nginx/Source_Code/html/
hooks:
  ApplicationStop:
    - location: /stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: /start_server
      timeout: 300
      runas: root
  

